// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/axod/pb/IPFS.proto

package net.axod.pb;

public final class IPFSProtos {
  private IPFSProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeltaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Delta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    java.util.List<java.lang.String>
        getAddedProtocolsList();
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    int getAddedProtocolsCount();
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    java.lang.String getAddedProtocols(int index);
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddedProtocolsBytes(int index);

    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    java.util.List<java.lang.String>
        getRmProtocolsList();
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    int getRmProtocolsCount();
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    java.lang.String getRmProtocols(int index);
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    com.google.protobuf.ByteString
        getRmProtocolsBytes(int index);
  }
  /**
   * Protobuf type {@code Delta}
   */
  public  static final class Delta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Delta)
      DeltaOrBuilder {
    // Use Delta.newBuilder() to construct.
    private Delta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Delta() {
      addedProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      rmProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Delta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                addedProtocols_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              addedProtocols_.add(bs);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rmProtocols_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              rmProtocols_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          addedProtocols_ = addedProtocols_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rmProtocols_ = rmProtocols_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.axod.pb.IPFSProtos.internal_static_Delta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.axod.pb.IPFSProtos.internal_static_Delta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.axod.pb.IPFSProtos.Delta.class, net.axod.pb.IPFSProtos.Delta.Builder.class);
    }

    public static final int ADDED_PROTOCOLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList addedProtocols_;
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddedProtocolsList() {
      return addedProtocols_;
    }
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    public int getAddedProtocolsCount() {
      return addedProtocols_.size();
    }
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    public java.lang.String getAddedProtocols(int index) {
      return addedProtocols_.get(index);
    }
    /**
     * <pre>
     * new protocols now serviced by the peer.
     * </pre>
     *
     * <code>repeated string added_protocols = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddedProtocolsBytes(int index) {
      return addedProtocols_.getByteString(index);
    }

    public static final int RM_PROTOCOLS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList rmProtocols_;
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRmProtocolsList() {
      return rmProtocols_;
    }
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    public int getRmProtocolsCount() {
      return rmProtocols_.size();
    }
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    public java.lang.String getRmProtocols(int index) {
      return rmProtocols_.get(index);
    }
    /**
     * <pre>
     * protocols dropped by the peer.
     * </pre>
     *
     * <code>repeated string rm_protocols = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRmProtocolsBytes(int index) {
      return rmProtocols_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < addedProtocols_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addedProtocols_.getRaw(i));
      }
      for (int i = 0; i < rmProtocols_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rmProtocols_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < addedProtocols_.size(); i++) {
          dataSize += computeStringSizeNoTag(addedProtocols_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddedProtocolsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rmProtocols_.size(); i++) {
          dataSize += computeStringSizeNoTag(rmProtocols_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRmProtocolsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.axod.pb.IPFSProtos.Delta)) {
        return super.equals(obj);
      }
      net.axod.pb.IPFSProtos.Delta other = (net.axod.pb.IPFSProtos.Delta) obj;

      boolean result = true;
      result = result && getAddedProtocolsList()
          .equals(other.getAddedProtocolsList());
      result = result && getRmProtocolsList()
          .equals(other.getRmProtocolsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAddedProtocolsCount() > 0) {
        hash = (37 * hash) + ADDED_PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getAddedProtocolsList().hashCode();
      }
      if (getRmProtocolsCount() > 0) {
        hash = (37 * hash) + RM_PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getRmProtocolsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Delta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Delta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Delta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.axod.pb.IPFSProtos.Delta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Delta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Delta)
        net.axod.pb.IPFSProtos.DeltaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.axod.pb.IPFSProtos.internal_static_Delta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.axod.pb.IPFSProtos.internal_static_Delta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.axod.pb.IPFSProtos.Delta.class, net.axod.pb.IPFSProtos.Delta.Builder.class);
      }

      // Construct using net.axod.pb.IPFSProtos.Delta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        addedProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rmProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.axod.pb.IPFSProtos.internal_static_Delta_descriptor;
      }

      public net.axod.pb.IPFSProtos.Delta getDefaultInstanceForType() {
        return net.axod.pb.IPFSProtos.Delta.getDefaultInstance();
      }

      public net.axod.pb.IPFSProtos.Delta build() {
        net.axod.pb.IPFSProtos.Delta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.axod.pb.IPFSProtos.Delta buildPartial() {
        net.axod.pb.IPFSProtos.Delta result = new net.axod.pb.IPFSProtos.Delta(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          addedProtocols_ = addedProtocols_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.addedProtocols_ = addedProtocols_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          rmProtocols_ = rmProtocols_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rmProtocols_ = rmProtocols_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.axod.pb.IPFSProtos.Delta) {
          return mergeFrom((net.axod.pb.IPFSProtos.Delta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.axod.pb.IPFSProtos.Delta other) {
        if (other == net.axod.pb.IPFSProtos.Delta.getDefaultInstance()) return this;
        if (!other.addedProtocols_.isEmpty()) {
          if (addedProtocols_.isEmpty()) {
            addedProtocols_ = other.addedProtocols_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddedProtocolsIsMutable();
            addedProtocols_.addAll(other.addedProtocols_);
          }
          onChanged();
        }
        if (!other.rmProtocols_.isEmpty()) {
          if (rmProtocols_.isEmpty()) {
            rmProtocols_ = other.rmProtocols_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRmProtocolsIsMutable();
            rmProtocols_.addAll(other.rmProtocols_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.axod.pb.IPFSProtos.Delta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.axod.pb.IPFSProtos.Delta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList addedProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddedProtocolsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          addedProtocols_ = new com.google.protobuf.LazyStringArrayList(addedProtocols_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddedProtocolsList() {
        return addedProtocols_.getUnmodifiableView();
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public int getAddedProtocolsCount() {
        return addedProtocols_.size();
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public java.lang.String getAddedProtocols(int index) {
        return addedProtocols_.get(index);
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddedProtocolsBytes(int index) {
        return addedProtocols_.getByteString(index);
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public Builder setAddedProtocols(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddedProtocolsIsMutable();
        addedProtocols_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public Builder addAddedProtocols(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddedProtocolsIsMutable();
        addedProtocols_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public Builder addAllAddedProtocols(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddedProtocolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addedProtocols_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public Builder clearAddedProtocols() {
        addedProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * new protocols now serviced by the peer.
       * </pre>
       *
       * <code>repeated string added_protocols = 1;</code>
       */
      public Builder addAddedProtocolsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddedProtocolsIsMutable();
        addedProtocols_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList rmProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRmProtocolsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rmProtocols_ = new com.google.protobuf.LazyStringArrayList(rmProtocols_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRmProtocolsList() {
        return rmProtocols_.getUnmodifiableView();
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public int getRmProtocolsCount() {
        return rmProtocols_.size();
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public java.lang.String getRmProtocols(int index) {
        return rmProtocols_.get(index);
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRmProtocolsBytes(int index) {
        return rmProtocols_.getByteString(index);
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public Builder setRmProtocols(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRmProtocolsIsMutable();
        rmProtocols_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public Builder addRmProtocols(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRmProtocolsIsMutable();
        rmProtocols_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public Builder addAllRmProtocols(
          java.lang.Iterable<java.lang.String> values) {
        ensureRmProtocolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rmProtocols_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public Builder clearRmProtocols() {
        rmProtocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols dropped by the peer.
       * </pre>
       *
       * <code>repeated string rm_protocols = 2;</code>
       */
      public Builder addRmProtocolsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRmProtocolsIsMutable();
        rmProtocols_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Delta)
    }

    // @@protoc_insertion_point(class_scope:Delta)
    private static final net.axod.pb.IPFSProtos.Delta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.axod.pb.IPFSProtos.Delta();
    }

    public static net.axod.pb.IPFSProtos.Delta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Delta>
        PARSER = new com.google.protobuf.AbstractParser<Delta>() {
      public Delta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Delta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Delta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Delta> getParserForType() {
      return PARSER;
    }

    public net.axod.pb.IPFSProtos.Delta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdentifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Identify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    boolean hasProtocolVersion();
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    java.lang.String getProtocolVersion();
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    com.google.protobuf.ByteString
        getProtocolVersionBytes();

    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    boolean hasAgentVersion();
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    java.lang.String getAgentVersion();
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    com.google.protobuf.ByteString
        getAgentVersionBytes();

    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     */
    boolean hasPublicKey();
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getListenAddrsList();
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    int getListenAddrsCount();
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    com.google.protobuf.ByteString getListenAddrs(int index);

    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     */
    boolean hasObservedAddr();
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     */
    com.google.protobuf.ByteString getObservedAddr();

    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    java.util.List<java.lang.String>
        getProtocolsList();
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    int getProtocolsCount();
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    java.lang.String getProtocols(int index);
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    com.google.protobuf.ByteString
        getProtocolsBytes(int index);

    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    boolean hasDelta();
    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    net.axod.pb.IPFSProtos.Delta getDelta();
    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    net.axod.pb.IPFSProtos.DeltaOrBuilder getDeltaOrBuilder();

    /**
     * <pre>
     * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
     * signed by the sending node. It contains the same addresses as the listenAddrs field, but
     * in a form that lets us share authenticated addrs with other peers.
     * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
     * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
     * </pre>
     *
     * <code>optional bytes signedPeerRecord = 8;</code>
     */
    boolean hasSignedPeerRecord();
    /**
     * <pre>
     * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
     * signed by the sending node. It contains the same addresses as the listenAddrs field, but
     * in a form that lets us share authenticated addrs with other peers.
     * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
     * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
     * </pre>
     *
     * <code>optional bytes signedPeerRecord = 8;</code>
     */
    com.google.protobuf.ByteString getSignedPeerRecord();
  }
  /**
   * Protobuf type {@code Identify}
   */
  public  static final class Identify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Identify)
      IdentifyOrBuilder {
    // Use Identify.newBuilder() to construct.
    private Identify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Identify() {
      protocolVersion_ = "";
      agentVersion_ = "";
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      listenAddrs_ = java.util.Collections.emptyList();
      observedAddr_ = com.google.protobuf.ByteString.EMPTY;
      protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      signedPeerRecord_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Identify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000004;
              publicKey_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                listenAddrs_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              listenAddrs_.add(input.readBytes());
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                protocols_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              protocols_.add(bs);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              observedAddr_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              protocolVersion_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              agentVersion_ = bs;
              break;
            }
            case 58: {
              net.axod.pb.IPFSProtos.Delta.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = delta_.toBuilder();
              }
              delta_ = input.readMessage(net.axod.pb.IPFSProtos.Delta.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(delta_);
                delta_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 66: {
              bitField0_ |= 0x00000020;
              signedPeerRecord_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          listenAddrs_ = java.util.Collections.unmodifiableList(listenAddrs_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          protocols_ = protocols_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.axod.pb.IPFSProtos.internal_static_Identify_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.axod.pb.IPFSProtos.internal_static_Identify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.axod.pb.IPFSProtos.Identify.class, net.axod.pb.IPFSProtos.Identify.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOLVERSION_FIELD_NUMBER = 5;
    private volatile java.lang.Object protocolVersion_;
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    public java.lang.String getProtocolVersion() {
      java.lang.Object ref = protocolVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          protocolVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * protocolVersion determines compatibility between peers
     * </pre>
     *
     * <code>optional string protocolVersion = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolVersionBytes() {
      java.lang.Object ref = protocolVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGENTVERSION_FIELD_NUMBER = 6;
    private volatile java.lang.Object agentVersion_;
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    public boolean hasAgentVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    public java.lang.String getAgentVersion() {
      java.lang.Object ref = agentVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agentVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
     * includes the client name and client.
     * </pre>
     *
     * <code>optional string agentVersion = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAgentVersionBytes() {
      java.lang.Object ref = agentVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * publicKey is this node's public key (which also gives its node.ID)
     * - may not need to be sent, as secure channel implies it has been sent.
     * - then again, if we change / disable secure channel, may still want it.
     * </pre>
     *
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int LISTENADDRS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> listenAddrs_;
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getListenAddrsList() {
      return listenAddrs_;
    }
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    public int getListenAddrsCount() {
      return listenAddrs_.size();
    }
    /**
     * <pre>
     * listenAddrs are the multiaddrs the sender node listens for open connections on
     * </pre>
     *
     * <code>repeated bytes listenAddrs = 2;</code>
     */
    public com.google.protobuf.ByteString getListenAddrs(int index) {
      return listenAddrs_.get(index);
    }

    public static final int OBSERVEDADDR_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString observedAddr_;
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     */
    public boolean hasObservedAddr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
     * this is useful information to convey to the other side, as it helps the remote endpoint
     * determine whether its connection to the local peer goes through NAT.
     * </pre>
     *
     * <code>optional bytes observedAddr = 4;</code>
     */
    public com.google.protobuf.ByteString getObservedAddr() {
      return observedAddr_;
    }

    public static final int PROTOCOLS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList protocols_;
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProtocolsList() {
      return protocols_;
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    public int getProtocolsCount() {
      return protocols_.size();
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    public java.lang.String getProtocols(int index) {
      return protocols_.get(index);
    }
    /**
     * <pre>
     * protocols are the services this node is running
     * </pre>
     *
     * <code>repeated string protocols = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolsBytes(int index) {
      return protocols_.getByteString(index);
    }

    public static final int DELTA_FIELD_NUMBER = 7;
    private net.axod.pb.IPFSProtos.Delta delta_;
    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    public net.axod.pb.IPFSProtos.Delta getDelta() {
      return delta_ == null ? net.axod.pb.IPFSProtos.Delta.getDefaultInstance() : delta_;
    }
    /**
     * <pre>
     * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
     * </pre>
     *
     * <code>optional .Delta delta = 7;</code>
     */
    public net.axod.pb.IPFSProtos.DeltaOrBuilder getDeltaOrBuilder() {
      return delta_ == null ? net.axod.pb.IPFSProtos.Delta.getDefaultInstance() : delta_;
    }

    public static final int SIGNEDPEERRECORD_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString signedPeerRecord_;
    /**
     * <pre>
     * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
     * signed by the sending node. It contains the same addresses as the listenAddrs field, but
     * in a form that lets us share authenticated addrs with other peers.
     * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
     * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
     * </pre>
     *
     * <code>optional bytes signedPeerRecord = 8;</code>
     */
    public boolean hasSignedPeerRecord() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
     * signed by the sending node. It contains the same addresses as the listenAddrs field, but
     * in a form that lets us share authenticated addrs with other peers.
     * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
     * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
     * </pre>
     *
     * <code>optional bytes signedPeerRecord = 8;</code>
     */
    public com.google.protobuf.ByteString getSignedPeerRecord() {
      return signedPeerRecord_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(1, publicKey_);
      }
      for (int i = 0; i < listenAddrs_.size(); i++) {
        output.writeBytes(2, listenAddrs_.get(i));
      }
      for (int i = 0; i < protocols_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protocols_.getRaw(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, observedAddr_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, agentVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(7, getDelta());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, signedPeerRecord_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listenAddrs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(listenAddrs_.get(i));
        }
        size += dataSize;
        size += 1 * getListenAddrsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < protocols_.size(); i++) {
          dataSize += computeStringSizeNoTag(protocols_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProtocolsList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, observedAddr_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, agentVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getDelta());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, signedPeerRecord_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.axod.pb.IPFSProtos.Identify)) {
        return super.equals(obj);
      }
      net.axod.pb.IPFSProtos.Identify other = (net.axod.pb.IPFSProtos.Identify) obj;

      boolean result = true;
      result = result && (hasProtocolVersion() == other.hasProtocolVersion());
      if (hasProtocolVersion()) {
        result = result && getProtocolVersion()
            .equals(other.getProtocolVersion());
      }
      result = result && (hasAgentVersion() == other.hasAgentVersion());
      if (hasAgentVersion()) {
        result = result && getAgentVersion()
            .equals(other.getAgentVersion());
      }
      result = result && (hasPublicKey() == other.hasPublicKey());
      if (hasPublicKey()) {
        result = result && getPublicKey()
            .equals(other.getPublicKey());
      }
      result = result && getListenAddrsList()
          .equals(other.getListenAddrsList());
      result = result && (hasObservedAddr() == other.hasObservedAddr());
      if (hasObservedAddr()) {
        result = result && getObservedAddr()
            .equals(other.getObservedAddr());
      }
      result = result && getProtocolsList()
          .equals(other.getProtocolsList());
      result = result && (hasDelta() == other.hasDelta());
      if (hasDelta()) {
        result = result && getDelta()
            .equals(other.getDelta());
      }
      result = result && (hasSignedPeerRecord() == other.hasSignedPeerRecord());
      if (hasSignedPeerRecord()) {
        result = result && getSignedPeerRecord()
            .equals(other.getSignedPeerRecord());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion().hashCode();
      }
      if (hasAgentVersion()) {
        hash = (37 * hash) + AGENTVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getAgentVersion().hashCode();
      }
      if (hasPublicKey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKey().hashCode();
      }
      if (getListenAddrsCount() > 0) {
        hash = (37 * hash) + LISTENADDRS_FIELD_NUMBER;
        hash = (53 * hash) + getListenAddrsList().hashCode();
      }
      if (hasObservedAddr()) {
        hash = (37 * hash) + OBSERVEDADDR_FIELD_NUMBER;
        hash = (53 * hash) + getObservedAddr().hashCode();
      }
      if (getProtocolsCount() > 0) {
        hash = (37 * hash) + PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolsList().hashCode();
      }
      if (hasDelta()) {
        hash = (37 * hash) + DELTA_FIELD_NUMBER;
        hash = (53 * hash) + getDelta().hashCode();
      }
      if (hasSignedPeerRecord()) {
        hash = (37 * hash) + SIGNEDPEERRECORD_FIELD_NUMBER;
        hash = (53 * hash) + getSignedPeerRecord().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Identify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Identify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.IPFSProtos.Identify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.axod.pb.IPFSProtos.Identify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Identify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Identify)
        net.axod.pb.IPFSProtos.IdentifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.axod.pb.IPFSProtos.internal_static_Identify_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.axod.pb.IPFSProtos.internal_static_Identify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.axod.pb.IPFSProtos.Identify.class, net.axod.pb.IPFSProtos.Identify.Builder.class);
      }

      // Construct using net.axod.pb.IPFSProtos.Identify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDeltaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        protocolVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        agentVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        listenAddrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        observedAddr_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (deltaBuilder_ == null) {
          delta_ = null;
        } else {
          deltaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        signedPeerRecord_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.axod.pb.IPFSProtos.internal_static_Identify_descriptor;
      }

      public net.axod.pb.IPFSProtos.Identify getDefaultInstanceForType() {
        return net.axod.pb.IPFSProtos.Identify.getDefaultInstance();
      }

      public net.axod.pb.IPFSProtos.Identify build() {
        net.axod.pb.IPFSProtos.Identify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.axod.pb.IPFSProtos.Identify buildPartial() {
        net.axod.pb.IPFSProtos.Identify result = new net.axod.pb.IPFSProtos.Identify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protocolVersion_ = protocolVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.agentVersion_ = agentVersion_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.publicKey_ = publicKey_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          listenAddrs_ = java.util.Collections.unmodifiableList(listenAddrs_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.listenAddrs_ = listenAddrs_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.observedAddr_ = observedAddr_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          protocols_ = protocols_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.protocols_ = protocols_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        if (deltaBuilder_ == null) {
          result.delta_ = delta_;
        } else {
          result.delta_ = deltaBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.signedPeerRecord_ = signedPeerRecord_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.axod.pb.IPFSProtos.Identify) {
          return mergeFrom((net.axod.pb.IPFSProtos.Identify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.axod.pb.IPFSProtos.Identify other) {
        if (other == net.axod.pb.IPFSProtos.Identify.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          bitField0_ |= 0x00000001;
          protocolVersion_ = other.protocolVersion_;
          onChanged();
        }
        if (other.hasAgentVersion()) {
          bitField0_ |= 0x00000002;
          agentVersion_ = other.agentVersion_;
          onChanged();
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (!other.listenAddrs_.isEmpty()) {
          if (listenAddrs_.isEmpty()) {
            listenAddrs_ = other.listenAddrs_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureListenAddrsIsMutable();
            listenAddrs_.addAll(other.listenAddrs_);
          }
          onChanged();
        }
        if (other.hasObservedAddr()) {
          setObservedAddr(other.getObservedAddr());
        }
        if (!other.protocols_.isEmpty()) {
          if (protocols_.isEmpty()) {
            protocols_ = other.protocols_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureProtocolsIsMutable();
            protocols_.addAll(other.protocols_);
          }
          onChanged();
        }
        if (other.hasDelta()) {
          mergeDelta(other.getDelta());
        }
        if (other.hasSignedPeerRecord()) {
          setSignedPeerRecord(other.getSignedPeerRecord());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.axod.pb.IPFSProtos.Identify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.axod.pb.IPFSProtos.Identify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object protocolVersion_ = "";
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public java.lang.String getProtocolVersion() {
        java.lang.Object ref = protocolVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            protocolVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolVersionBytes() {
        java.lang.Object ref = protocolVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protocolVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public Builder setProtocolVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protocolVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = getDefaultInstance().getProtocolVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocolVersion determines compatibility between peers
       * </pre>
       *
       * <code>optional string protocolVersion = 5;</code>
       */
      public Builder setProtocolVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        protocolVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object agentVersion_ = "";
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public boolean hasAgentVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public java.lang.String getAgentVersion() {
        java.lang.Object ref = agentVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            agentVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAgentVersionBytes() {
        java.lang.Object ref = agentVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agentVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public Builder setAgentVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        agentVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public Builder clearAgentVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        agentVersion_ = getDefaultInstance().getAgentVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * agentVersion is like a UserAgent string in browsers, or client version in bittorrent
       * includes the client name and client.
       * </pre>
       *
       * <code>optional string agentVersion = 6;</code>
       */
      public Builder setAgentVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        agentVersion_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       */
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * publicKey is this node's public key (which also gives its node.ID)
       * - may not need to be sent, as secure channel implies it has been sent.
       * - then again, if we change / disable secure channel, may still want it.
       * </pre>
       *
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> listenAddrs_ = java.util.Collections.emptyList();
      private void ensureListenAddrsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          listenAddrs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(listenAddrs_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getListenAddrsList() {
        return java.util.Collections.unmodifiableList(listenAddrs_);
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public int getListenAddrsCount() {
        return listenAddrs_.size();
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public com.google.protobuf.ByteString getListenAddrs(int index) {
        return listenAddrs_.get(index);
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public Builder setListenAddrs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenAddrsIsMutable();
        listenAddrs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public Builder addListenAddrs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListenAddrsIsMutable();
        listenAddrs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public Builder addAllListenAddrs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureListenAddrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listenAddrs_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * listenAddrs are the multiaddrs the sender node listens for open connections on
       * </pre>
       *
       * <code>repeated bytes listenAddrs = 2;</code>
       */
      public Builder clearListenAddrs() {
        listenAddrs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString observedAddr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       */
      public boolean hasObservedAddr() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       */
      public com.google.protobuf.ByteString getObservedAddr() {
        return observedAddr_;
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       */
      public Builder setObservedAddr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        observedAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * oservedAddr is the multiaddr of the remote endpoint that the sender node perceives
       * this is useful information to convey to the other side, as it helps the remote endpoint
       * determine whether its connection to the local peer goes through NAT.
       * </pre>
       *
       * <code>optional bytes observedAddr = 4;</code>
       */
      public Builder clearObservedAddr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        observedAddr_ = getDefaultInstance().getObservedAddr();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProtocolsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          protocols_ = new com.google.protobuf.LazyStringArrayList(protocols_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getProtocolsList() {
        return protocols_.getUnmodifiableView();
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public int getProtocolsCount() {
        return protocols_.size();
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public java.lang.String getProtocols(int index) {
        return protocols_.get(index);
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolsBytes(int index) {
        return protocols_.getByteString(index);
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public Builder setProtocols(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public Builder addProtocols(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public Builder addAllProtocols(
          java.lang.Iterable<java.lang.String> values) {
        ensureProtocolsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, protocols_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public Builder clearProtocols() {
        protocols_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * protocols are the services this node is running
       * </pre>
       *
       * <code>repeated string protocols = 3;</code>
       */
      public Builder addProtocolsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProtocolsIsMutable();
        protocols_.add(value);
        onChanged();
        return this;
      }

      private net.axod.pb.IPFSProtos.Delta delta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.axod.pb.IPFSProtos.Delta, net.axod.pb.IPFSProtos.Delta.Builder, net.axod.pb.IPFSProtos.DeltaOrBuilder> deltaBuilder_;
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public net.axod.pb.IPFSProtos.Delta getDelta() {
        if (deltaBuilder_ == null) {
          return delta_ == null ? net.axod.pb.IPFSProtos.Delta.getDefaultInstance() : delta_;
        } else {
          return deltaBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public Builder setDelta(net.axod.pb.IPFSProtos.Delta value) {
        if (deltaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          delta_ = value;
          onChanged();
        } else {
          deltaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public Builder setDelta(
          net.axod.pb.IPFSProtos.Delta.Builder builderForValue) {
        if (deltaBuilder_ == null) {
          delta_ = builderForValue.build();
          onChanged();
        } else {
          deltaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public Builder mergeDelta(net.axod.pb.IPFSProtos.Delta value) {
        if (deltaBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              delta_ != null &&
              delta_ != net.axod.pb.IPFSProtos.Delta.getDefaultInstance()) {
            delta_ =
              net.axod.pb.IPFSProtos.Delta.newBuilder(delta_).mergeFrom(value).buildPartial();
          } else {
            delta_ = value;
          }
          onChanged();
        } else {
          deltaBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public Builder clearDelta() {
        if (deltaBuilder_ == null) {
          delta_ = null;
          onChanged();
        } else {
          deltaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public net.axod.pb.IPFSProtos.Delta.Builder getDeltaBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getDeltaFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      public net.axod.pb.IPFSProtos.DeltaOrBuilder getDeltaOrBuilder() {
        if (deltaBuilder_ != null) {
          return deltaBuilder_.getMessageOrBuilder();
        } else {
          return delta_ == null ?
              net.axod.pb.IPFSProtos.Delta.getDefaultInstance() : delta_;
        }
      }
      /**
       * <pre>
       * a delta update is incompatible with everything else. If this field is included, none of the others can appear.
       * </pre>
       *
       * <code>optional .Delta delta = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.axod.pb.IPFSProtos.Delta, net.axod.pb.IPFSProtos.Delta.Builder, net.axod.pb.IPFSProtos.DeltaOrBuilder> 
          getDeltaFieldBuilder() {
        if (deltaBuilder_ == null) {
          deltaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.axod.pb.IPFSProtos.Delta, net.axod.pb.IPFSProtos.Delta.Builder, net.axod.pb.IPFSProtos.DeltaOrBuilder>(
                  getDelta(),
                  getParentForChildren(),
                  isClean());
          delta_ = null;
        }
        return deltaBuilder_;
      }

      private com.google.protobuf.ByteString signedPeerRecord_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
       * signed by the sending node. It contains the same addresses as the listenAddrs field, but
       * in a form that lets us share authenticated addrs with other peers.
       * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
       * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
       * </pre>
       *
       * <code>optional bytes signedPeerRecord = 8;</code>
       */
      public boolean hasSignedPeerRecord() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
       * signed by the sending node. It contains the same addresses as the listenAddrs field, but
       * in a form that lets us share authenticated addrs with other peers.
       * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
       * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
       * </pre>
       *
       * <code>optional bytes signedPeerRecord = 8;</code>
       */
      public com.google.protobuf.ByteString getSignedPeerRecord() {
        return signedPeerRecord_;
      }
      /**
       * <pre>
       * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
       * signed by the sending node. It contains the same addresses as the listenAddrs field, but
       * in a form that lets us share authenticated addrs with other peers.
       * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
       * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
       * </pre>
       *
       * <code>optional bytes signedPeerRecord = 8;</code>
       */
      public Builder setSignedPeerRecord(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        signedPeerRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * signedPeerRecord contains a serialized SignedEnvelope containing a PeerRecord,
       * signed by the sending node. It contains the same addresses as the listenAddrs field, but
       * in a form that lets us share authenticated addrs with other peers.
       * see github.com/libp2p/go-libp2p-core/record/pb/envelope.proto and
       * github.com/libp2p/go-libp2p-core/peer/pb/peer_record.proto for message definitions.
       * </pre>
       *
       * <code>optional bytes signedPeerRecord = 8;</code>
       */
      public Builder clearSignedPeerRecord() {
        bitField0_ = (bitField0_ & ~0x00000080);
        signedPeerRecord_ = getDefaultInstance().getSignedPeerRecord();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Identify)
    }

    // @@protoc_insertion_point(class_scope:Identify)
    private static final net.axod.pb.IPFSProtos.Identify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.axod.pb.IPFSProtos.Identify();
    }

    public static net.axod.pb.IPFSProtos.Identify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Identify>
        PARSER = new com.google.protobuf.AbstractParser<Identify>() {
      public Identify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Identify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Identify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Identify> getParserForType() {
      return PARSER;
    }

    public net.axod.pb.IPFSProtos.Identify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Delta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Delta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Identify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Identify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026net/axod/pb/IPFS.proto\"6\n\005Delta\022\027\n\017add" +
      "ed_protocols\030\001 \003(\t\022\024\n\014rm_protocols\030\002 \003(\t" +
      "\"\273\001\n\010Identify\022\027\n\017protocolVersion\030\005 \001(\t\022\024" +
      "\n\014agentVersion\030\006 \001(\t\022\021\n\tpublicKey\030\001 \001(\014\022" +
      "\023\n\013listenAddrs\030\002 \003(\014\022\024\n\014observedAddr\030\004 \001" +
      "(\014\022\021\n\tprotocols\030\003 \003(\t\022\025\n\005delta\030\007 \001(\0132\006.D" +
      "elta\022\030\n\020signedPeerRecord\030\010 \001(\014B\031\n\013net.ax" +
      "od.pbB\nIPFSProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Delta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Delta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Delta_descriptor,
        new java.lang.String[] { "AddedProtocols", "RmProtocols", });
    internal_static_Identify_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Identify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Identify_descriptor,
        new java.lang.String[] { "ProtocolVersion", "AgentVersion", "PublicKey", "ListenAddrs", "ObservedAddr", "Protocols", "Delta", "SignedPeerRecord", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
