// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/axod/pb/NoisePayload.proto

package net.axod.pb;

public final class NoisePayload {
  private NoisePayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NoiseHandshakePayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.NoiseHandshakePayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes identity_key = 1;</code>
     */
    com.google.protobuf.ByteString getIdentityKey();

    /**
     * <code>optional bytes identity_sig = 2;</code>
     */
    com.google.protobuf.ByteString getIdentitySig();

    /**
     * <code>optional bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code pb.NoiseHandshakePayload}
   */
  public  static final class NoiseHandshakePayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.NoiseHandshakePayload)
      NoiseHandshakePayloadOrBuilder {
    // Use NoiseHandshakePayload.newBuilder() to construct.
    private NoiseHandshakePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoiseHandshakePayload() {
      identityKey_ = com.google.protobuf.ByteString.EMPTY;
      identitySig_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NoiseHandshakePayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              identityKey_ = input.readBytes();
              break;
            }
            case 18: {

              identitySig_ = input.readBytes();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.axod.pb.NoisePayload.internal_static_pb_NoiseHandshakePayload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.axod.pb.NoisePayload.internal_static_pb_NoiseHandshakePayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.axod.pb.NoisePayload.NoiseHandshakePayload.class, net.axod.pb.NoisePayload.NoiseHandshakePayload.Builder.class);
    }

    public static final int IDENTITY_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString identityKey_;
    /**
     * <code>optional bytes identity_key = 1;</code>
     */
    public com.google.protobuf.ByteString getIdentityKey() {
      return identityKey_;
    }

    public static final int IDENTITY_SIG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identitySig_;
    /**
     * <code>optional bytes identity_sig = 2;</code>
     */
    public com.google.protobuf.ByteString getIdentitySig() {
      return identitySig_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!identityKey_.isEmpty()) {
        output.writeBytes(1, identityKey_);
      }
      if (!identitySig_.isEmpty()) {
        output.writeBytes(2, identitySig_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!identityKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, identityKey_);
      }
      if (!identitySig_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, identitySig_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.axod.pb.NoisePayload.NoiseHandshakePayload)) {
        return super.equals(obj);
      }
      net.axod.pb.NoisePayload.NoiseHandshakePayload other = (net.axod.pb.NoisePayload.NoiseHandshakePayload) obj;

      boolean result = true;
      result = result && getIdentityKey()
          .equals(other.getIdentityKey());
      result = result && getIdentitySig()
          .equals(other.getIdentitySig());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IDENTITY_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityKey().hashCode();
      hash = (37 * hash) + IDENTITY_SIG_FIELD_NUMBER;
      hash = (53 * hash) + getIdentitySig().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.NoisePayload.NoiseHandshakePayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.axod.pb.NoisePayload.NoiseHandshakePayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.NoiseHandshakePayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.NoiseHandshakePayload)
        net.axod.pb.NoisePayload.NoiseHandshakePayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.axod.pb.NoisePayload.internal_static_pb_NoiseHandshakePayload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.axod.pb.NoisePayload.internal_static_pb_NoiseHandshakePayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.axod.pb.NoisePayload.NoiseHandshakePayload.class, net.axod.pb.NoisePayload.NoiseHandshakePayload.Builder.class);
      }

      // Construct using net.axod.pb.NoisePayload.NoiseHandshakePayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identityKey_ = com.google.protobuf.ByteString.EMPTY;

        identitySig_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.axod.pb.NoisePayload.internal_static_pb_NoiseHandshakePayload_descriptor;
      }

      public net.axod.pb.NoisePayload.NoiseHandshakePayload getDefaultInstanceForType() {
        return net.axod.pb.NoisePayload.NoiseHandshakePayload.getDefaultInstance();
      }

      public net.axod.pb.NoisePayload.NoiseHandshakePayload build() {
        net.axod.pb.NoisePayload.NoiseHandshakePayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.axod.pb.NoisePayload.NoiseHandshakePayload buildPartial() {
        net.axod.pb.NoisePayload.NoiseHandshakePayload result = new net.axod.pb.NoisePayload.NoiseHandshakePayload(this);
        result.identityKey_ = identityKey_;
        result.identitySig_ = identitySig_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.axod.pb.NoisePayload.NoiseHandshakePayload) {
          return mergeFrom((net.axod.pb.NoisePayload.NoiseHandshakePayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.axod.pb.NoisePayload.NoiseHandshakePayload other) {
        if (other == net.axod.pb.NoisePayload.NoiseHandshakePayload.getDefaultInstance()) return this;
        if (other.getIdentityKey() != com.google.protobuf.ByteString.EMPTY) {
          setIdentityKey(other.getIdentityKey());
        }
        if (other.getIdentitySig() != com.google.protobuf.ByteString.EMPTY) {
          setIdentitySig(other.getIdentitySig());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.axod.pb.NoisePayload.NoiseHandshakePayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.axod.pb.NoisePayload.NoiseHandshakePayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString identityKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identity_key = 1;</code>
       */
      public com.google.protobuf.ByteString getIdentityKey() {
        return identityKey_;
      }
      /**
       * <code>optional bytes identity_key = 1;</code>
       */
      public Builder setIdentityKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identity_key = 1;</code>
       */
      public Builder clearIdentityKey() {
        
        identityKey_ = getDefaultInstance().getIdentityKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString identitySig_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identity_sig = 2;</code>
       */
      public com.google.protobuf.ByteString getIdentitySig() {
        return identitySig_;
      }
      /**
       * <code>optional bytes identity_sig = 2;</code>
       */
      public Builder setIdentitySig(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identitySig_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identity_sig = 2;</code>
       */
      public Builder clearIdentitySig() {
        
        identitySig_ = getDefaultInstance().getIdentitySig();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pb.NoiseHandshakePayload)
    }

    // @@protoc_insertion_point(class_scope:pb.NoiseHandshakePayload)
    private static final net.axod.pb.NoisePayload.NoiseHandshakePayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.axod.pb.NoisePayload.NoiseHandshakePayload();
    }

    public static net.axod.pb.NoisePayload.NoiseHandshakePayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoiseHandshakePayload>
        PARSER = new com.google.protobuf.AbstractParser<NoiseHandshakePayload>() {
      public NoiseHandshakePayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NoiseHandshakePayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NoiseHandshakePayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoiseHandshakePayload> getParserForType() {
      return PARSER;
    }

    public net.axod.pb.NoisePayload.NoiseHandshakePayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_NoiseHandshakePayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_NoiseHandshakePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036net/axod/pb/NoisePayload.proto\022\002pb\"Q\n\025" +
      "NoiseHandshakePayload\022\024\n\014identity_key\030\001 " +
      "\001(\014\022\024\n\014identity_sig\030\002 \001(\014\022\014\n\004data\030\003 \001(\014B" +
      "\033\n\013net.axod.pbB\014NoisePayloadb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_NoiseHandshakePayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_NoiseHandshakePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_NoiseHandshakePayload_descriptor,
        new java.lang.String[] { "IdentityKey", "IdentitySig", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
