// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/axod/pb/secio.proto

package net.axod.pb;

public final class SecioProtos {
  private SecioProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProposeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Propose)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes rand = 1;</code>
     */
    boolean hasRand();
    /**
     * <code>optional bytes rand = 1;</code>
     */
    com.google.protobuf.ByteString getRand();

    /**
     * <code>optional bytes pubkey = 2;</code>
     */
    boolean hasPubkey();
    /**
     * <code>optional bytes pubkey = 2;</code>
     */
    com.google.protobuf.ByteString getPubkey();

    /**
     * <code>optional string exchanges = 3;</code>
     */
    boolean hasExchanges();
    /**
     * <code>optional string exchanges = 3;</code>
     */
    java.lang.String getExchanges();
    /**
     * <code>optional string exchanges = 3;</code>
     */
    com.google.protobuf.ByteString
        getExchangesBytes();

    /**
     * <code>optional string ciphers = 4;</code>
     */
    boolean hasCiphers();
    /**
     * <code>optional string ciphers = 4;</code>
     */
    java.lang.String getCiphers();
    /**
     * <code>optional string ciphers = 4;</code>
     */
    com.google.protobuf.ByteString
        getCiphersBytes();

    /**
     * <code>optional string hashes = 5;</code>
     */
    boolean hasHashes();
    /**
     * <code>optional string hashes = 5;</code>
     */
    java.lang.String getHashes();
    /**
     * <code>optional string hashes = 5;</code>
     */
    com.google.protobuf.ByteString
        getHashesBytes();
  }
  /**
   * Protobuf type {@code Propose}
   */
  public  static final class Propose extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Propose)
      ProposeOrBuilder {
    // Use Propose.newBuilder() to construct.
    private Propose(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Propose() {
      rand_ = com.google.protobuf.ByteString.EMPTY;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
      exchanges_ = "";
      ciphers_ = "";
      hashes_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Propose(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rand_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pubkey_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              exchanges_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ciphers_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              hashes_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.axod.pb.SecioProtos.internal_static_Propose_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.axod.pb.SecioProtos.internal_static_Propose_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.axod.pb.SecioProtos.Propose.class, net.axod.pb.SecioProtos.Propose.Builder.class);
    }

    private int bitField0_;
    public static final int RAND_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rand_;
    /**
     * <code>optional bytes rand = 1;</code>
     */
    public boolean hasRand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes rand = 1;</code>
     */
    public com.google.protobuf.ByteString getRand() {
      return rand_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>optional bytes pubkey = 2;</code>
     */
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes pubkey = 2;</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }

    public static final int EXCHANGES_FIELD_NUMBER = 3;
    private volatile java.lang.Object exchanges_;
    /**
     * <code>optional string exchanges = 3;</code>
     */
    public boolean hasExchanges() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string exchanges = 3;</code>
     */
    public java.lang.String getExchanges() {
      java.lang.Object ref = exchanges_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exchanges_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exchanges = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExchangesBytes() {
      java.lang.Object ref = exchanges_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchanges_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CIPHERS_FIELD_NUMBER = 4;
    private volatile java.lang.Object ciphers_;
    /**
     * <code>optional string ciphers = 4;</code>
     */
    public boolean hasCiphers() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ciphers = 4;</code>
     */
    public java.lang.String getCiphers() {
      java.lang.Object ref = ciphers_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ciphers_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ciphers = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCiphersBytes() {
      java.lang.Object ref = ciphers_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ciphers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASHES_FIELD_NUMBER = 5;
    private volatile java.lang.Object hashes_;
    /**
     * <code>optional string hashes = 5;</code>
     */
    public boolean hasHashes() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string hashes = 5;</code>
     */
    public java.lang.String getHashes() {
      java.lang.Object ref = hashes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hashes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hashes = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHashesBytes() {
      java.lang.Object ref = hashes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, rand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, pubkey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exchanges_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ciphers_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hashes_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rand_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pubkey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, exchanges_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ciphers_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hashes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.axod.pb.SecioProtos.Propose)) {
        return super.equals(obj);
      }
      net.axod.pb.SecioProtos.Propose other = (net.axod.pb.SecioProtos.Propose) obj;

      boolean result = true;
      result = result && (hasRand() == other.hasRand());
      if (hasRand()) {
        result = result && getRand()
            .equals(other.getRand());
      }
      result = result && (hasPubkey() == other.hasPubkey());
      if (hasPubkey()) {
        result = result && getPubkey()
            .equals(other.getPubkey());
      }
      result = result && (hasExchanges() == other.hasExchanges());
      if (hasExchanges()) {
        result = result && getExchanges()
            .equals(other.getExchanges());
      }
      result = result && (hasCiphers() == other.hasCiphers());
      if (hasCiphers()) {
        result = result && getCiphers()
            .equals(other.getCiphers());
      }
      result = result && (hasHashes() == other.hasHashes());
      if (hasHashes()) {
        result = result && getHashes()
            .equals(other.getHashes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRand()) {
        hash = (37 * hash) + RAND_FIELD_NUMBER;
        hash = (53 * hash) + getRand().hashCode();
      }
      if (hasPubkey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubkey().hashCode();
      }
      if (hasExchanges()) {
        hash = (37 * hash) + EXCHANGES_FIELD_NUMBER;
        hash = (53 * hash) + getExchanges().hashCode();
      }
      if (hasCiphers()) {
        hash = (37 * hash) + CIPHERS_FIELD_NUMBER;
        hash = (53 * hash) + getCiphers().hashCode();
      }
      if (hasHashes()) {
        hash = (37 * hash) + HASHES_FIELD_NUMBER;
        hash = (53 * hash) + getHashes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.axod.pb.SecioProtos.Propose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Propose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Propose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Propose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.axod.pb.SecioProtos.Propose prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Propose}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Propose)
        net.axod.pb.SecioProtos.ProposeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.axod.pb.SecioProtos.internal_static_Propose_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.axod.pb.SecioProtos.internal_static_Propose_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.axod.pb.SecioProtos.Propose.class, net.axod.pb.SecioProtos.Propose.Builder.class);
      }

      // Construct using net.axod.pb.SecioProtos.Propose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rand_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        pubkey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        exchanges_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ciphers_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        hashes_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.axod.pb.SecioProtos.internal_static_Propose_descriptor;
      }

      public net.axod.pb.SecioProtos.Propose getDefaultInstanceForType() {
        return net.axod.pb.SecioProtos.Propose.getDefaultInstance();
      }

      public net.axod.pb.SecioProtos.Propose build() {
        net.axod.pb.SecioProtos.Propose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.axod.pb.SecioProtos.Propose buildPartial() {
        net.axod.pb.SecioProtos.Propose result = new net.axod.pb.SecioProtos.Propose(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rand_ = rand_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pubkey_ = pubkey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.exchanges_ = exchanges_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ciphers_ = ciphers_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hashes_ = hashes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.axod.pb.SecioProtos.Propose) {
          return mergeFrom((net.axod.pb.SecioProtos.Propose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.axod.pb.SecioProtos.Propose other) {
        if (other == net.axod.pb.SecioProtos.Propose.getDefaultInstance()) return this;
        if (other.hasRand()) {
          setRand(other.getRand());
        }
        if (other.hasPubkey()) {
          setPubkey(other.getPubkey());
        }
        if (other.hasExchanges()) {
          bitField0_ |= 0x00000004;
          exchanges_ = other.exchanges_;
          onChanged();
        }
        if (other.hasCiphers()) {
          bitField0_ |= 0x00000008;
          ciphers_ = other.ciphers_;
          onChanged();
        }
        if (other.hasHashes()) {
          bitField0_ |= 0x00000010;
          hashes_ = other.hashes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.axod.pb.SecioProtos.Propose parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.axod.pb.SecioProtos.Propose) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rand_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes rand = 1;</code>
       */
      public boolean hasRand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes rand = 1;</code>
       */
      public com.google.protobuf.ByteString getRand() {
        return rand_;
      }
      /**
       * <code>optional bytes rand = 1;</code>
       */
      public Builder setRand(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes rand = 1;</code>
       */
      public Builder clearRand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rand_ = getDefaultInstance().getRand();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pubkey = 2;</code>
       */
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return pubkey_;
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pubkey = 2;</code>
       */
      public Builder clearPubkey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }

      private java.lang.Object exchanges_ = "";
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public boolean hasExchanges() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public java.lang.String getExchanges() {
        java.lang.Object ref = exchanges_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchanges_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExchangesBytes() {
        java.lang.Object ref = exchanges_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchanges_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public Builder setExchanges(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exchanges_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public Builder clearExchanges() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exchanges_ = getDefaultInstance().getExchanges();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchanges = 3;</code>
       */
      public Builder setExchangesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        exchanges_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ciphers_ = "";
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public boolean hasCiphers() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public java.lang.String getCiphers() {
        java.lang.Object ref = ciphers_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ciphers_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCiphersBytes() {
        java.lang.Object ref = ciphers_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ciphers_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public Builder setCiphers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ciphers_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public Builder clearCiphers() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ciphers_ = getDefaultInstance().getCiphers();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ciphers = 4;</code>
       */
      public Builder setCiphersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ciphers_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hashes_ = "";
      /**
       * <code>optional string hashes = 5;</code>
       */
      public boolean hasHashes() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string hashes = 5;</code>
       */
      public java.lang.String getHashes() {
        java.lang.Object ref = hashes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hashes_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hashes = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHashesBytes() {
        java.lang.Object ref = hashes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hashes = 5;</code>
       */
      public Builder setHashes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hashes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashes = 5;</code>
       */
      public Builder clearHashes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hashes_ = getDefaultInstance().getHashes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashes = 5;</code>
       */
      public Builder setHashesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hashes_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Propose)
    }

    // @@protoc_insertion_point(class_scope:Propose)
    private static final net.axod.pb.SecioProtos.Propose DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.axod.pb.SecioProtos.Propose();
    }

    public static net.axod.pb.SecioProtos.Propose getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Propose>
        PARSER = new com.google.protobuf.AbstractParser<Propose>() {
      public Propose parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Propose(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Propose> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Propose> getParserForType() {
      return PARSER;
    }

    public net.axod.pb.SecioProtos.Propose getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Exchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes epubkey = 1;</code>
     */
    boolean hasEpubkey();
    /**
     * <code>optional bytes epubkey = 1;</code>
     */
    com.google.protobuf.ByteString getEpubkey();

    /**
     * <code>optional bytes signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code Exchange}
   */
  public  static final class Exchange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Exchange)
      ExchangeOrBuilder {
    // Use Exchange.newBuilder() to construct.
    private Exchange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exchange() {
      epubkey_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Exchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              epubkey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.axod.pb.SecioProtos.internal_static_Exchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.axod.pb.SecioProtos.internal_static_Exchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.axod.pb.SecioProtos.Exchange.class, net.axod.pb.SecioProtos.Exchange.Builder.class);
    }

    private int bitField0_;
    public static final int EPUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString epubkey_;
    /**
     * <code>optional bytes epubkey = 1;</code>
     */
    public boolean hasEpubkey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes epubkey = 1;</code>
     */
    public com.google.protobuf.ByteString getEpubkey() {
      return epubkey_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, epubkey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, epubkey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.axod.pb.SecioProtos.Exchange)) {
        return super.equals(obj);
      }
      net.axod.pb.SecioProtos.Exchange other = (net.axod.pb.SecioProtos.Exchange) obj;

      boolean result = true;
      result = result && (hasEpubkey() == other.hasEpubkey());
      if (hasEpubkey()) {
        result = result && getEpubkey()
            .equals(other.getEpubkey());
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasEpubkey()) {
        hash = (37 * hash) + EPUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getEpubkey().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Exchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Exchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.axod.pb.SecioProtos.Exchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.axod.pb.SecioProtos.Exchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Exchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Exchange)
        net.axod.pb.SecioProtos.ExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.axod.pb.SecioProtos.internal_static_Exchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.axod.pb.SecioProtos.internal_static_Exchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.axod.pb.SecioProtos.Exchange.class, net.axod.pb.SecioProtos.Exchange.Builder.class);
      }

      // Construct using net.axod.pb.SecioProtos.Exchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        epubkey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.axod.pb.SecioProtos.internal_static_Exchange_descriptor;
      }

      public net.axod.pb.SecioProtos.Exchange getDefaultInstanceForType() {
        return net.axod.pb.SecioProtos.Exchange.getDefaultInstance();
      }

      public net.axod.pb.SecioProtos.Exchange build() {
        net.axod.pb.SecioProtos.Exchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.axod.pb.SecioProtos.Exchange buildPartial() {
        net.axod.pb.SecioProtos.Exchange result = new net.axod.pb.SecioProtos.Exchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.epubkey_ = epubkey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.axod.pb.SecioProtos.Exchange) {
          return mergeFrom((net.axod.pb.SecioProtos.Exchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.axod.pb.SecioProtos.Exchange other) {
        if (other == net.axod.pb.SecioProtos.Exchange.getDefaultInstance()) return this;
        if (other.hasEpubkey()) {
          setEpubkey(other.getEpubkey());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.axod.pb.SecioProtos.Exchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.axod.pb.SecioProtos.Exchange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString epubkey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes epubkey = 1;</code>
       */
      public boolean hasEpubkey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       */
      public com.google.protobuf.ByteString getEpubkey() {
        return epubkey_;
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       */
      public Builder setEpubkey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        epubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes epubkey = 1;</code>
       */
      public Builder clearEpubkey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        epubkey_ = getDefaultInstance().getEpubkey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Exchange)
    }

    // @@protoc_insertion_point(class_scope:Exchange)
    private static final net.axod.pb.SecioProtos.Exchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.axod.pb.SecioProtos.Exchange();
    }

    public static net.axod.pb.SecioProtos.Exchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Exchange>
        PARSER = new com.google.protobuf.AbstractParser<Exchange>() {
      public Exchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Exchange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Exchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exchange> getParserForType() {
      return PARSER;
    }

    public net.axod.pb.SecioProtos.Exchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Propose_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Propose_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exchange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exchange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027net/axod/pb/secio.proto\"[\n\007Propose\022\014\n\004" +
      "rand\030\001 \001(\014\022\016\n\006pubkey\030\002 \001(\014\022\021\n\texchanges\030" +
      "\003 \001(\t\022\017\n\007ciphers\030\004 \001(\t\022\016\n\006hashes\030\005 \001(\t\"." +
      "\n\010Exchange\022\017\n\007epubkey\030\001 \001(\014\022\021\n\tsignature" +
      "\030\002 \001(\014B\032\n\013net.axod.pbB\013SecioProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Propose_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Propose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Propose_descriptor,
        new java.lang.String[] { "Rand", "Pubkey", "Exchanges", "Ciphers", "Hashes", });
    internal_static_Exchange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Exchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exchange_descriptor,
        new java.lang.String[] { "Epubkey", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
